packages:
  - packages/**
  - apps/**
  - '!apps/next/.next/**'

allowBuilds:
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
