packages:
  - packages/**
  - apps/**
  - "!apps/next/.next/**"
minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - "@infonomic/*"
allowBuilds:
  esbuild: true
  sharp: true
  '@biomejs/biome': true
  protobufjs: true
  unrs-resolver: true
